### PR TITLE
made worker filter examples more promenent with different example types

### PR DESCRIPTION
**Pull request by vanphan24**
[Preview link](https://boundary-cb9yco51w-hashicorp.vercel.app/boundary/docs/concepts/filtering/worker-tags
)
Made some changes to make worker filter examples more obvious and referenceable for end users on our /boundary/docs/concepts/filtering/worker-tags page.
- Added examples worker filters for targets, vault cred stores, and storage buckets. 
- Added CLI examples and UI example screenshots in dark and light mode.

### CODE REVIEW

**Comment by dannyjknights** [comment]
This is great @vanphan24 . I'm just thinking for completeness in your examples, if we could add a Terraform tab and have something like:

`resource "boundary_target" "aws" {
  type                               = "ssh"
  name                             = "aws-ec2"
  description                    = "AWS EC2 Targets"
  egress_worker_filter     = " \"sm-ingress-upstream-worker1\" in \"/tags/type\" "`

or something like that?

**Comment by stellarsquall** [comment]
> This is great @vanphan24 . I'm just thinking for completeness in your examples, if we could add a Terraform tab and have something like:
> 
> ```
> resource "boundary_target" "aws" {
>   type                               = "ssh"
>   name                             = "aws-ec2"
>   description                    = "AWS EC2 Targets"
>   egress_worker_filter     = " \"prod\" in \"/tags/type\" "
> ```
> 
> or something like that?

I went ahead and added Terraform tags with some examples. Can you check them out and see if there's any issues?

**Comment by dannyjknights** [comment]
@stellarsquall could you add a space after the first quotation mark and before the last one like this, please:

` egress_worker_filter     = " \"prod\" in \"/tags/type\" "`

the example shows it like this:

` egress_worker_filter     = "\"prod\" in \"/tags/type\""`

**Comment by dannyjknights** [comment]
@stellarsquall Regarding the below:

```
resource "boundary_credential_store_vault" "vault_cred_store" {
  name          = "Vault host credentials"
  address       = "http://127.0.0.1:8200"       # change to Vault address
  token         = "s.0ufRo6XEGU2jOqnIr7OlFYP5"  # change to valid Vault token
  scope_id      = boundary_scope.project.id     # change to target scope
  worker_filter = "\"vault\" in \"/tags/type\"" # change to valid Vault worker filter
}
```
the worker_filter is to facilitate access to a private vault. What are you thoughts on just calling that out, or do you think it will make it too verbose? This is an HCP only attribute so could be worth a mention?

**Comment by stellarsquall** [comment]
> @stellarsquall Regarding the below:
> 
> ```
> resource "boundary_credential_store_vault" "vault_cred_store" {
>   name          = "Vault host credentials"
>   address       = "http://127.0.0.1:8200"       # change to Vault address
>   token         = "s.0ufRo6XEGU2jOqnIr7OlFYP5"  # change to valid Vault token
>   scope_id      = boundary_scope.project.id     # change to target scope
>   worker_filter = "\"vault\" in \"/tags/type\"" # change to valid Vault worker filter
> }
> ```
> 
> the worker_filter is to facilitate access to a private vault. What are you thoughts on just calling that out, or do you think it will make it too verbose? This is an HCP only attribute so could be worth a mention?

yeah that makes sense @dannyjknights, is this enough or does it need more?

```
resource "boundary_credential_store_vault" "vault_cred_store" {
  name          = "Vault host credentials"
  address       = "http://127.0.0.1:8200"       # change to Vault address
  token         = "s.0ufRo6XEGU2jOqnIr7OlFYP5"  # change to valid Vault token
  scope_id      = boundary_scope.project.id     # change to target scope
  worker_filter = "\"vault\" in \"/tags/type\"" # change to access private Vault cluster
}
```

**Comment by dannyjknights** [comment]
Yeah that's great @stellarsquall. To be honest I completely missed the wording at the top of that section that does a good job calling it out, but I think the change in comment for that line helps cement it in. Thank you

**Review by stellarsquall — APPROVED** [review]
great work on this everyone!

**Pull request merged**
