### PR TITLE
docs: Credential management documentation

### PR DESCRIPTION
**Pull request by Dan-Heath**
This pull request adds new a new topic to the documentation, "Credential management" based on [Adam's Google Doc](https://docs.google.com/document/d/1o3TUXtXy5GHouXYCa8Ho1rAGOv-xwZu_-epkhej6b9U/edit#). It compares credential brokering to credential injection.

[View the page in the preview deployment](https://boundary-ez7x5ixpm-hashicorp.vercel.app/boundary/docs/concepts/credential-management).

### CODE REVIEW

**Review by AdamBouhmad — APPROVED** [review]
for a v1, this LGTM!

**Comment by stellarsquall** [comment]
The main thing I'm noticing about the deploy preview is that the animated GIFs render very large, while the terminal demo reads very small. 

Can we modify the sizes of these assets?

**Comment by Dan-Heath** [comment]
> The main thing I'm noticing about the deploy preview is that the animated GIFs render very large, while the terminal demo reads very small.
> 
> Can we modify the sizes of these assets?

Yeah, we thought this all looked kind of lopsided too. Resizing has been a little tricky, due to the animations. I played with this today and got the brokering and injection GIFs resized so that they are closer in size to the static graphics and terminal GIF. It looks less lopsided, but somehow in the process, the GIFS are only playing through one time instead of looping now in the latest build:

https://boundary-1b5yp410q-hashicorp.vercel.app/boundary/docs/concepts/credential-management

I also haven't been able to make the terminal GIF appear larger yet, b/c it is already downsizing to fit the browser. I am playing with the idea of having a link here that people can click to get a larger version, but I'm trying to figure out how to accomplish it in Markdown. I will play with these 2 issues a bit more tomorrow.

**Comment by Dan-Heath** [comment]
> The main thing I'm noticing about the deploy preview is that the animated GIFs render very large, while the terminal demo reads very small.
> 
> Can we modify the sizes of these assets?

I think these issues are significantly improved in the latest version. I was able to reduce the size of the animated GIFs and increase the size of the demo. The GIFs are looping continuously now, as well. What do you think @stellarsquall ?

https://boundary-d06rnctm6-hashicorp.vercel.app/boundary/docs/concepts/credential-management

Thanks for the review!

**Review by stellarsquall — APPROVED** [review]
so great!

**Pull request merged**
