### PR TITLE
refact (kms): convert to the new stdlib slices pkg

### PR DESCRIPTION
**Pull request by jimlambrt**
(cherry picked from commit e2f98de696af6ec06b314383d9e27e82140d76e5)

### CODE REVIEW

**Review by ddebko — CHANGES_REQUESTED** [review]
There are some weird gen delta errors for missing fields in some proto definitions

**Comment by jimlambrt** [comment]
> There are some weird gen delta errors for missing fields in some proto definitions

It's unlikely, these errors can't be coming from my PR.  There's nothing in the PR that has to do with protos.

**Comment by jimlambrt** [comment]
looks like the `release/0.14.x` branch has issues with protos before this PR.
```
❯ make proto
# First check all protos except controller/servers and controller/storage for WIRE_JSON compatibility
cd internal/proto && buf breaking --against 'https://github.com/hashicorp/boundary.git#branch=stable-website,subdir=internal/proto' \
                --exclude-path=controller/servers \
                --exclude-path=controller/storage \
                --config buf.breaking.json.yaml
/Users/jimlambrt/workspaces/github/hashicorp/boundary-prs/internal/proto
controller/api/resources/targets/v1/target.proto:299:1:Previously present field "102" with name "endpoint_port" on message "SessionAuthorizationData" was deleted without reserving the name "endpoint_port".
controller/api/resources/targets/v1/target.proto:299:1:Previously present field "105" with name "expiration" on message "SessionAuthorizationData" was deleted without reserving the name "expiration".
controller/api/resources/targets/v1/target.proto:338:1:Previously present field "102" with name "endpoint_port" on message "SessionAuthorization" was deleted without reserving the name "endpoint_port".
controller/api/resources/targets/v1/target.proto:338:1:Previously present field "105" with name "expiration" on message "SessionAuthorization" was deleted without reserving the name "expiration".
make: *** [protolint] Error 100
 ~/workspaces/github/hashicorp/boundary-prs  release/0.14.x *21 
```

**Comment by jimlambrt** [comment]
the `make gen` errors are caused by the script looking at `main` as the source of truth for changes and the `release/0.1.4x` branch doesn't have these proto fields.

**Pull request merged**
