### PR TITLE
Add methods to get attributes more easily in Go API

### PR DESCRIPTION
**Pull request by jefferai**

### CODE REVIEW

**Review by johanbrandhorst — COMMENTED** [review]
Approach looks reasonable to me, provided that it works 😛.

**Comment by jefferai** [comment]
@johanbrandhorst Did some manual testing and it seems fine. Added an extra check, see waht you think?

**Review by johanbrandhorst — APPROVED** [review]
Ooh that type check is nice

**Comment by jefferai** [comment]
TY!

**Pull request merged**
