### PR TITLE
enos(smoke): Test brokered credential

### PR DESCRIPTION
**Pull request by louisruch**
enos(smoke): Test brokered credential consumption instead of manually
passing private key to boundary connect

### CODE REVIEW

**Comment by louisruch** [comment]
@ryancragun @ddebko PTAL
I noticed that we could easily extend the brokered consumption behavior of ssh private keys recently added to Boundary when I had a transient failure on this path.

**Review by johanbrandhorst — APPROVED** [review]
This is awesome!

**Comment by louisruch** [comment]
@moduli Might be worth updating the e2e test connect using brokered credential consumption at some point as well

**Comment by moduli** [comment]
> @moduli Might be worth updating the e2e test connect using brokered credential consumption at some point as well

Yup! We're actively working on a new test that uses Vault to provide credentials. We'll also later add a test that uses boundary's built-in credential store (we'll use this as a model).

**Pull request merged**
