### PR TITLE
Have fallback eventing use json format

### PR DESCRIPTION
**Pull request by jefferai**

### CODE REVIEW

**Comment by jimlambrt** [comment]
@jefferai I'm not convinced this approach will work given: https://github.com/hashicorp/boundary/blob/f5bf3b2c0ca14c49b1f96fac9990bd320240c105/internal/observability/event/context.go#L281

we can discuss next week the best path forward.

**Comment by jefferai** [comment]
That's fair. I've also been thinking about it and wondering if our fallback shouldn't be to just write events directly to the output. E.g. if we were going to send to hclog on stderr, maybe just keep a global mutex on the fallback writer and write events out directly to stderr.

**Comment by jimlambrt** [comment]
@jefferai I pushed some commits to try and move this PR forward.

**Review by jefferai — COMMENTED** [review]
Looks good to me

**Review by jimlambrt — APPROVED** [review]

**Pull request merged**
