### PR TITLE
Update configure-controllers.mdx

### PR DESCRIPTION
**Pull request by lpassig**
Not correct based on: 
https://developer.hashicorp.com/boundary/docs/configuration/controller#public_cluster_addr and https://github.com/hashicorp/boundary/issues/847

### CODE REVIEW

**Comment by lpassig** [comment]
@Dan-Heath

**Review by Dan-Heath — APPROVED** [review]
That looks correct to me, thank you!

**Comment by Dan-Heath** [comment]
Thanks very much for this submission @lpassig ! Have you signed the [Contributor License Agreement](https://github.com/hashicorp/boundary/pull/3407#issuecomment-1630660000)? I think you will need to if we want to merge this pull request. (If you did sign it, sometimes there is a delay.)

FYI @stellarsquall , I think this would need to be updated in [Enterprise deployment tutorial](https://developer.hashicorp.com/boundary/tutorials/enterprise/ent-deployment-guide#configure-boundary-controllers) as well.

**Comment by stellarsquall** [comment]
Thanks all! 

I've updated the deployment guide tutorial. Once the CLA is signed here by @lpassig we can merge the docs update.

**Comment by lpassig** [comment]
CLA signed 😄

**Comment by Dan-Heath** [comment]
> CLA signed 😄

Thank you @lpassig !

**Pull request merged**
